# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [1]:
import main
import numpy as np
import scipy
import pandas as pd

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [2]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)


Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.

In [3]:
print(main.cylinder_area(5.567,5))
print(main.cylinder_area(-1,5))
print(main.cylinder_area(5,-3))
print(main.cylinder_area(-5,-4))
#sprawdzenie działania funkcji poprzez wywołanie każdej możliwej konfiguracji

369.6177313577616
nan
nan
nan


***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [4]:
print(np.arange(1,13,1.5))
print(np.arange(1,14,1.5))
print(np.linspace(5,25,4))
"""
w podanych powyzej przykladach zostaly zastosowane dwie funkcje, arange ktora w tym przypadku tworzy wektor z zakresu 1-14, oraz posiada zadeklarowany skok o 1.5, linspace z drugiej strony
działa zupełnie inaczej ponieważ tak jak arange ma zadeklarowany zakres 5-25 jednak w przypadku tej funkcji wybieramy liczbe elementow ktore ma zawierac wektor, wtedy do niej dostowany jest skok
pomiedzy poszczegolnymi wyrazami, warto dodać że w przypadku arange wykorzystywany jest gotowy skok, przez co moze nie zostac w pelni wykorzystany zakres zadeklarowanych elementow co widac
na drugim przykladzie, ponad to przedział z ktorego wybierane sa elementy jest lewostronnie zamkniety i prawostronnie otwarty
"""

[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5]
[ 1.   2.5  4.   5.5  7.   8.5 10.  11.5 13. ]
[ 5.         11.66666667 18.33333333 25.        ]


'\nw podanych powyzej przykladach zostaly zastosowane dwie funkcje, arange ktora w tym przypadku tworzy wektor z zakresu 1-14, oraz posiada zadeklarowany skok o 1.5, linspace z drugiej strony\ndziała zupełnie inaczej ponieważ tak jak arange ma zadeklarowany zakres 5-25 jednak w przypadku tej funkcji wybieramy liczbe elementow ktore ma zawierac wektor, wtedy do niej dostowany jest skok\npomiedzy poszczegolnymi wyrazami, warto dodać że w przypadku arange wykorzystywany jest gotowy skok, przez co moze nie zostac w pelni wykorzystany zakres zadeklarowanych elementow co widac\nna drugim przykladzie, ponad to przedział z ktorego wybierane sa elementy jest lewostronnie zamkniety i prawostronnie otwarty\n'

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [5]:
print(main.fib(4))
print(main.fib(-5))
print(main.fib(1))
print(main.fib(0))
#sprawdzenie działania funkcji dla kazdej konfiguracji mogacej sprawic problemy w dzialaniu programu

[0 1 1 2 3]
None
[0 1]
[0]


***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [6]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [7]:
print(main.matrix_calculations(3))
print(main.matrix_calculations(1))
print(main.matrix_calculations(0))
#wywołanie funkcji dla przykładowych wartości, ponad to dla 0 wyznacznik macierzy jest rowny zero, przez co tym wywolaniem sprawdzamy zabezpieczenie przeciw tworzeniu macierzy odwrotnej dla
#macierzy, ktora nie powinna posiadac macierzy odwrotnej

(array([[ 0.11111111,  0.55555556, -0.22222222],
       [ 0.16666667,  0.33333333,  0.16666667],
       [-0.16666667,  0.66666667, -0.16666667]]), array([[ 3,  0, -3],
       [ 1,  1,  3],
       [-3,  1,  1]]), -17.999999999999996)
(array([[ 0. ,  1. , -1. ],
       [ 0.5,  0. ,  0.5],
       [-0.5,  1. , -0.5]]), array([[ 1,  0, -1],
       [ 1,  1,  1],
       [-1,  1,  1]]), -2.0)
nan


***Zadanie 5.***  
Stwórz w notatniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [8]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


In [9]:
M = np.array([[3,1,-2,4],[0,1,1,5],[-2,1,1,6],[4,3,0,1]])
M11 = M[0,0]
M33 = M[2,2]
M32 = M[2,1]
print("Punkt o współrzędnych (1,1): ", M11)
print("Punkt o współrzędnych (3,3): ", M33)
print("Punkt o współrzędnych (3,2): ", M32)
wektor1 = M[:,2]
wektor2 = M[1,:]
print("Elementy trzeciej kolumny: ", wektor1)
print("Elementy drugiego wiersza:", wektor2 )
#w przypadku tworzenia macierzy zamiast stosować np.array mozna uzyc komendy np.matrix ktora w tym przypadku uzyska ten sam efekt, majac na uwadze wskazowki z wczesniej podanego przykladu,
#wypisanie poszczegolnych punktow macierzy, wekotorow poziomych i kolumnowych jest bardzo szybkie

Punkt o współrzędnych (1,1):  3
Punkt o współrzędnych (3,3):  1
Punkt o współrzędnych (3,2):  1
Elementy trzeciej kolumny:  [-2  1  1  0]
Elementy drugiego wiersza: [0 1 1 5]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [10]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [12]:
print(main.custom_matrix(4,6))
print(main.custom_matrix(5,3))
print(main.custom_matrix(4,4))
print(main.custom_matrix(-1,4))
print(main.custom_matrix(-1,-2))
print(main.custom_matrix(0,0))
#sprawdzenie dzialania macierzy w kazdym przypadku, gdy m > n, m < n oraz m = n, w przypadku nieprawdilowych wartosci powinien zostac zwrocony None

[[1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]
 [1. 2. 3. 4. 5. 6.]]
[[1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]
 [5. 5. 5.]]
[[1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]
 [1. 2. 3. 4.]]
None
None
None


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [ ]:
vector1 = np.array([1, 3, 13]).T
vector2 = np.array([8, 5, -12]).T
print(np.multiply(4, vector1))
print(-vector2+np.array([2, 2, 2]).T)
print(np.dot(vector1,vector2))
print(np.multiply(vector1,vector2))
"""
w tym przypadku zarowno funkcje matmul jak i dot mozna stosowac wymiennie poniewaz w przypadku prostych wektorow i macierzy, zwracaja dokladnie to samo, jednak multiply dziala inaczej poniewaz
w przypadku mnozenia macierzy czy tez wektorow otrzymamy produkt wyjsciowy o tym samym wymiarze co pierwotny, w przypadku dzialan na wektorach stworzonych na bazie array i matrix mozna wykonywac
podstawowe operacje arytmetyczne
"""

[ 4 12 52]
[-6 -3 14]
-133
[   8   15 -156]


'\nw tym przypadku zarowno funkcje matmul jak i dot mozna stosowac wymiennie poniewaz w przypadku prostych wektorow i macierzy, zwracaja dokladnie to samo, jednak multiply dziala inaczej poniewaz\nw przypadku mnozenia macierzy czy tez wektorow otrzymamy produkt wyjsciowy o tym samym wymiarze co pierwotny, w przypadku dzialan na wektorach stworzonych na bazie array i matrix mozna wykonywac\npodstawowe operacje arytmetyczne\n'

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [ ]:
M1 = np.array([[1, -7, 3], [-12, 3, 4], [5, 13, -3]])
print(3*M1, "\n")
print(3*M1 + np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]]), "\n")
print(M1.T, "\n")
print(np.multiply(M1, vector1), "\n")
print(np.multiply(vector2.T, M1), "\n")
"""
Analogicznie jak w poprzednim zadaniu mozna bez problemow za pomoca wbudowanych funkcji wykonywac skomplikowanie jak i najprostsze operacje na macierzach i wektorach bez problemow
"""

[[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]] 

[[  4 -20  10]
 [-35  10  13]
 [ 16  40  -8]] 

[[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]] 

[[  1 -21  39]
 [-12   9  52]
 [  5  39 -39]] 

[[  8 -35 -36]
 [-96  15 -48]
 [ 40  65  36]] 



'\nAnalogicznie jak w poprzednim zadaniu mozna bez problemow za pomoca wbudowanych funkcji wykonywac skomplikowanie jak i najprostsze operacje na macierzach i wektorach bez problemow\n'

Podsumowujac, biblioteka numpy udostepniona wraz z dodatkowym oprogramowaniem Anaconda, jest bardzo bogatym rozszerzeniem dajacym wiele mozliwosci, dzialanie na macierzach, wektorach w normalny sposob wymagaja tworzenia bardzo trudnych funkcji, tak jak chocby w przypadku wyznaczania macierzy odwrotnej. Jednak ilosc funkcjonalnosci udostepnionych w ramach biblioteki numpy jest tak ogromna, ze pozwala to zaoszczedzic bardzo duzo czasu i korzystac z opracowanych juz algorytmow, przez co mozna skupic sie nie na ich implementacji, ale wykorzystaniu korzysci plynacych z otrzymanej funkcjonalnosci.

Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)